- hosts: all
  gather_facts: yes
  become: yes
  tasks:

# Run OS Baselines to Setup Systems
  - name: Baseline Ubuntu
    ansible.builtin.import_role:
      name: "murphywants-ansible-role-baseline-ubuntu"
    when:
      - ansible_distribution == 'Ubuntu'

# Run OS Baselines to Setup Proxmox
- hosts: os_proxmox
  become: yes
  tasks:
    - name: Baseline proxmox
      ansible.builtin.import_role:
        name: "murphywants-ansible-role-baseline-proxmox"

# Setup/Configure/Update Vaultwarden
- hosts: app_vaultwarden
  become: yes
  tasks: 
    - name: Setup Vaultwarden
      ansible.builtin.import_role:
        name: "murphywants-ansible-role-application-vaultwarden"

# Setup/Configure/Update Vaultwarden
- hosts: app_freshrss
  become: yes
  tasks:
    - name: Setup Freshrss
      ansible.builtin.import_role:
        name: "murphywants-ansible-role-application-Freshrss"

# Setup/Configure/Update Home Assistant
- hosts: app_home_assistant
  become: yes
  tasks:
    - name: Setup Home Assistant
      ansible.builtin.import_role:
        name: "murphywants-ansible-role-application-homeassistant"

- hosts: app_nextcloud
  become: yes
  tasks: 
    - name: Setup nextcloud
      ansible.builtin.import_role:
        name: "murphywants-ansible-role-application-nextcloud"

- hosts: app_grocy
  become: yes
  tasks: 
    - name: Setup grocy
      ansible.builtin.import_role:
        name: "murphywants-ansible-role-application-grocy"

- hosts: app_bookstack
  become: yes
  tasks: 
    - name: Setup bookstack
      ansible.builtin.import_role:
        name: "murphywants-ansible-role-application-bookstack"

- hosts: app_forgejo
  become: yes
  tasks: 
    - name: Setup forgejo
      ansible.builtin.import_role:
        name: "murphywants-ansible-role-application-forgejo"

- hosts: app_planka
  become: yes
  tasks: 
    - name: Setup planka
      ansible.builtin.import_role:
        name: "murphywants-ansible-role-application-planka"
