- hosts: all
  gather_facts: yes
  become: yes
  tasks:

  - name: Baseline Ubuntu
    ansible.builtin.import_role:
      name: "../ansible-roles/os-baseline/murphywants-ansible-role-baseline-ubuntu"
    when:
      - ansible_distribution == 'Ubuntu'



- hosts: app_vaultwarden
  become: yes
  tasks: 
    - name: Setup Vaultwarden
      ansible.builtin.import_role:
        name: "../ansible-roles/server_applications/murphywants-ansible-role-application-vaultwarden"


- hosts: app_freshrss
  become: yes
  tasks:
    - name: Setup Freshrss
      ansible.builtin.import_role:
        name: "../ansible-roles/server_applications/murphywants-ansible-role-application-Freshrss"

- hosts: app_home_assistant
  become: yes
  tasks:
    - name: Setup Home Assistant
      ansible.builtin.import_role:
        name: ../ansible-roles/server_applications/murphywants-ansible-role-application-homeassistant

