- hosts: all
  gather_facts: yes
  become: yes
  tasks:

# Run OS Baselines to Setup Systems
  - name: Baseline Ubuntu
    ansible.builtin.import_role:
      name: "murphywants-ansible-role-baseline-ubuntu"
    when:
      - ansible_distribution == 'Ubuntu'

# Run OS Baselines to Setup Proxmox
- hosts: os_proxmox
  become: yes
  tasks:
    - name: Baseline proxmox
      ansible.builtin.import_role:
        name: "murphywants-ansible-role-baseline-proxmox"

# Setup/Configure/Update Vaultwarden
- hosts: app_vaultwarden
  become: yes
  tasks: 
    - name: Setup Vaultwarden
      ansible.builtin.import_role:
        name: "murphywants-ansible-role-application-vaultwarden"

# Setup/Configure/Update Vaultwarden
- hosts: app_freshrss
  become: yes
  tasks:
    - name: Setup Freshrss
      ansible.builtin.import_role:
        name: "murphywants-ansible-role-application-Freshrss"

# Setup/Configure/Update Home Assistant
- hosts: app_home_assistant
  become: yes
  tasks:
    - name: Setup Home Assistant
      ansible.builtin.import_role:
        name: "murphywants-ansible-role-application-homeassistant"

