- hosts: all
  gather_facts: yes
  become: yes
  tasks:
  - name: Get Service facts
    ansible.builtin.service_facts:

  - name: Get Package Facts
    ansible.builtin.package_facts:

  - name: Print All Facts
    ansible.builtin.debug:
      var: ansible_facts
